### ISSUE TITLE
problem with example pubspec.yml

### ISSUE THREAD

**Issue by magick93** [kirbyfan64/vuedart#18]
Im trying to follow the example on https://refi64.com/vuedart/pages/intro.html

The `pubspec.yml` I am trying is:
```
name: vuedart_example
version: 0.1.0
description: VueDart example app
author: Foo Bar
dependencies:
  vue2: 0.3.2
  browser: any
dev_dependencies:
  build_runner:
  build_web_compilers: ^0.2.0
transformers:
  - vue2:
      # This is important!! See below.
      entry_points:
        - web/index.dart
```

This results in:
```
Working dir: /home/anton/Documents/tmp/my-project
/usr/lib/dart/bin/pub get
Resolving dependencies...
Because no versions of analyzer match >0.29.11 <0.30.0 and vue2 0.3.2 depends on analyzer ^0.29.11, vue2 0.3.2 requires analyzer 0.29.11.
And because analyzer 0.29.11 depends on cli_util ^0.0.1 and every version of build_web_compilers depends on cli_util ^0.1.2, vue2 0.3.2 is incompatible with build_web_compilers.
So, because vuedart_example depends on both vue2 0.3.2 and build_web_compilers ^0.2.0, version solving failed.
Process finished with exit code 1
```

I have also tried with `build_web_compilers: any` but get the same error.
